name: Lint Commit Messages
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "module.exports = {extends:['@commitlint/config-conventional']}" > ./commitlint.config.js
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional && npm install @commitlint/cli
      #- name : GITHUB CONTEXT
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      #  run: echo "$GITHUB_CONTEXT"
      - name: get commit message
        run: |
           for sha in $(curl ${{ github.event.pull_request.commits_url }} | jq '.[].sha' | sed 's/"//g')
           do
            echo "Sha: $sha"
           done
      - run: npx commitlint
      - uses: wagoid/commitlint-github-action@v2
      - uses: JulienKode/pull-request-name-linter-action@v0.2.0
        
