name: Lint Commit Messages
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "module.exports = {extends:['@commitlint/config-conventional']}" > ./commitlint.config.js
      #- uses: wagoid/commitlint-github-action@v2
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional @commitlint/cli
      - name: lint commit messages
        run: |
           for sha in $(curl ${{ github.event.pull_request.commits_url }} | jq '.[].sha' | sed 's/"//g')
           do
            git --no-pager log --format=%B -n 1 $sha | npx commitlint -V || true
           done
           echo ${{ github.event.pull_request.title }}
           echo ${{ github.event.pull_request }}
           echo ${{ github.event.pull_request.title }} | sed 's/"//g' | npx commitlint -V
      #- uses: JulienKode/pull-request-name-linter-action@v0.2.0
        
